export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_SUBJECT = "GET_SUBJECT";
export const GET_MYSUBJECT = "GET_MYSUBJECT";
export const DELETE_MYSUBJECT = "GET_SUBJECT";
export const APPLY_SUBJECT = "APPLY_SUBJECT";

export const ADD_EXCHANGE_SUBJECT = "ADD_EXCHANGE_SUBJECT";
export const SWITCH_EXCHANGE_SUBJECT = "SWITCH_EXCHANGE_SUBJECT";

export const APPLY_DRAW_SUBJECT = "APPLY_DRAW_SUBJECT";
export const GET_DRAW_SUBJECT = "GET_DRAW_SUBJECT";
export const DELETE_DRAW_SUBJECT = "GET_DRAW_SUBJECT";
